"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/usercontext/UserContext";
import { FavoritesProvider } from "@/contexts/favouritescontext/FavouritesContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <FavoritesProvider>{children}</FavoritesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
